CREATE TYPE "PetGender" AS ENUM ('MALE', 'FEMALE', 'UNKNOWN');

CREATE TYPE "PetSize" AS ENUM ('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE');

ALTER TABLE "User" ADD COLUMN "bio" TEXT;
ALTER TABLE "User" ADD COLUMN "city" TEXT;

ALTER TABLE "Pet" ADD COLUMN "bio" TEXT;
ALTER TABLE "Pet" ADD COLUMN "gender" "PetGender";
ALTER TABLE "Pet" ADD COLUMN "size" "PetSize";
ALTER TABLE "Pet" ADD COLUMN "temperament" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Pet" ADD COLUMN "city" TEXT;

CREATE INDEX "Pet_city_idx" ON "Pet"("city");
